
[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "none" #full
decorations_theme_variant = "Dark"

startup_mode = "Fullscreen"

[font]

normal.family = "FiraCode Nerd Font Mono"
bold.family = "FiraCode Nerd Font Mono"
italic.family = "FiraCode Nerd Font Mono"
bold_italic.family = "FiraCode Nerd Font Mono"

size = 12.0

[shell]
program = "/usr/bin/fish"

