github.com:
    users:
        lxrdxe7o:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: lxrdxe7o
